### ISSUE TITLE
UI/UX optimizations

### ISSUE THREAD

**Issue by J43fura** [ankaboot-source/wikiadviser#132]
- [x] SHARE and LINK are still uppercase, they should follow the design system policies #139 
- [x] #135
- [x] it lacks empty states almost everywhere (no changes for ex=>CTA "Edit your article"): https://polaris.shopify.com/components/layout-and-structure/empty-state #139 
- [x] disable Changes tab when there is no changes #148 
- [x] language picking by default use navigator locale
- [x] Wikipedia and WikiAdviser are always written this way, please respect the case #139 
- [x] the progress is weird, please make it more full screen, quasar spinners are nice if HUGE https://quasar.dev/vue-components/spinners especially the grid or the classical spinner or the dots, the engine is not suited at all with the content #139 
- [x] #136
- [x] #146 
- [x] Use « » or “ ” quotes instead of " #148 
- [x] #145
